name: 'Secret'

on:
  workflow_dispatch:

jobs:
  fetch_secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch-secrets
        with:
          access-id: ${{ vars.AKEYLESS_ACCESS_ID }}
          access-type: jwt
          static-secrets: |
            - name: "/sandbox/projects/github/static-test"
              output-name: "my_first_secret"

      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"
            echo "my_first_secret: ${{ steps.fetch-secrets.outputs.my_first_secret }}"
            
            echo "Environment Variables"
            echo "my_first_secret: ${{ env.my_first_secret }}"

            echo "Github Token: ${{ secrets.GITHUB_TOKEN }}"
